#! /bin/bash

# for example: ./install ias_v2.0.tar.gz
# 安装脚本实现步骤
# 1.判断服务是否在运行，如果运行，直接结束;
# 2.判断服务是否已安装，如果安装，备份一下;
# 3.解压安装包到安装目录;
# 4.建立直接启停服务软链接;
# 5.启动服务.

server_name=ias
server_start=ias_start
server_stop=ias_stop
install_dir=/usr/local/ias
backup_dir=/usr/local/ias_back
work_dir=$(cd $(dirname $0) && pwd)

# 判断参数个数
if [ $# -lt 1 ]
then
	echo "[ERROR] parameter nums is "$#" , while 1 was required, please retype."
	exit -1
fi

package_name=${1}

if [ ! -f ${package_name} ]; then
	echo "[ERROR] ${package_name} not exists."
	exit -1
fi

# 服务是否启动
pids=$(pidof ${server_name})
if [ ! -z "${pids}" ]; then
	echo "${server_name} already running, ${pids}"
	echo "stop first, please wait ..."
	kill -s term ${pids}

	sleep 3
	
	pids=$(pidof ${server_name})
	if [ ! -z "${pids}" ]; then
		echo "[ERROR] stop failed, please check, ${pids}"
		exit -1
	fi
	
	echo "stop succeed."
fi

# 服务是否安装
if [ -d ${install_dir} ]; then
	echo "${server_name} already installed, backup & remove, please wait..."
	
	if [ ! -d ${backup_dir} ]; then
		mkdir -p ${backup_dir}
	fi

	backup_name=${backup_dir}/${server_name}_$(date "+%Y-%m-%d_%H-%M-%S").tar.gz
	tar -zcvf ${backup_name} ${install_dir}
	
	rm -fr ${install_dir};
fi

# 解压安装包到安装目录
tar -zxvf ${package_name} -C /

# 建立直接启停服务软链接
if [ ! -f "/usr/bin/${server_start}" ]; then
	echo "ln -s ${install_dir}/${server_start}.sh /usr/bin/${server_start}"
	ln -s ${install_dir}/${server_start}.sh /usr/bin/${server_start}
fi
if [ ! -f "/usr/bin/${server_stop}" ]; then
	echo "ln -s ${install_dir}/${server_stop}.sh /usr/bin/${server_stop}"
	ln -s ${install_dir}/${server_stop}.sh /usr/bin/${server_stop}
fi

# 启动服务
${server_start}

echo "Installation completed."
